# Generated by Django 5.1.4 on 2024-12-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoresponder', '0002_remove_organization_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='official_token',
            field=models.TextField(max_length=255, verbose_name='Токен для API'),
        ),
    ]
